version: "3.7"
services:
  server:
    restart: unless-stopped
    user: "1000:1000"
    links:
      - db
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/home/node/app/src
      - ./server/nodemon.json:/home/node/app/nodemon.json
    network_mode: host
    container_name: media-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    expose:
      - "8755"
    ports:
      - "8755:8755"
    env_file:
      - ./server/.env
    command: npm run dev
  db:
    image: postgres:latest
    container_name: media-db
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGNAME}
      - POSTGRES_PORT=5432
    ports:
      - "5430:5432"
    expose:
      - "5432"
    volumes:
      - ./server/initdb.sql:/docker-entrypoint-initdb.d/database-seed.sql