version: "3.7"
services:
  server:
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    volumes:
      - ./server/src:/home/node/app/src
      - ./server/nodemon.json:/home/node/app/nodemon.json
      - /data/test:/home/node/app/media
    container_name: media-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    expose:
      - "8755"
    ports:
      - "8755:8755"
    command: npm run dev
  db:
    image: postgres:latest
    container_name: media-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGNAME}
      - POSTGRES_PORT=5432
    ports:
      - "5430:5432"
    expose:
      - "5432"
    volumes:
      - /data/postgres/dev/mediaserver:/var/lib/postgres/data
