name: ci-checks
on: [push]
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
      working-directory: ./server
    - run: npm test
      working-directory: ./server
    - run: npm build
      working-directory: ./server